version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 6
  complex-logic:
    enabled: true
    config:
      threshold: 8
  file-lines:
    enabled: true
    config:
      threshold: 1000
  method-complexity:
    enabled: true
    config:
      threshold: 30
  method-count:
    enabled: true
    config:
      threshold: 50
  method-lines:
    enabled: true
    config:
      threshold: 200
  nested-control-flow:
    enabled: true
    config:
      threshold: 8
  return-statements:
    enabled: true
    config:
      threshold: 6
  similar-code:
    enabled: true
  identical-code:
    enabled: true
exclude_patterns:
  - "demo/"
  - "dist/"
  - "__tests__/"
  - "gulpfile.js"
plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
  stylelint:
    enabled: true
